version: '3.9'
services: 
  postgres: 
    container_name: POSTGRES_DB
    image: postgres:13
    ports:                         
      - "5432:5432"                 
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres       
    networks:
      - user_project
      
  user_app: 
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@POSTGRES_DB:5432/postgres  
    ports: 
      - "3000:3000"                 
    depends_on:
      - postgres
    networks:                      
      - user_project

networks:                         
  user_project: