version: '3.9'
services: 
  postgres: 
    image: postgres
    ports:                         
      - "5432:5432"                 
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - user_project
      
  user_app: 
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    ports: 
      - "3000:3000"                
    depends_on:
      - postgres
    networks:                       
      - user_project

networks:                           
  user_project: