version: "3.9"

services: 
  app: 
    build: .
    
    port:
     - 3000:3000
    environment:
      - postgresql://postgres:mysecrepassword@postgres:5432/postgres
    depends_on:
      - postgres
    networks:
      - user_project

  postgres: 
    image: postgres:13
    environment: 
     - POSTGRES_PASSWORD=mysecrepassword
     - POSTGRES_DB=postgres
    networks:
      - user_project

networks: 
  user_project: